### PR TITLE
Rewrite for Nova 4

### PR DESCRIPTION
**Pull request by mbardelmeijer**
This PR rewrites how the links are rendered by using the native `MenuSection` & `MenuItem` from Nova.

I'll recommend creating a `2.0` version based of this, and having the `1.0` range for Nova 3.0

### CODE REVIEW

**Comment by vmitchell85** [comment]
@mbardelmeijer can you update this PR with the changes from #6 and I'll try to tag a 2.0 today.

**Comment by vmitchell85** [comment]
@mbardelmeijer I have tagged a [release candidate](https://github.com/vmitchell85/nova-links/releases/tag/v2.0RC). If you could give a quick test and provide some feedback that'd be great.

Please note I did make some changes, the [README.md](https://github.com/vmitchell85/nova-links/blob/develop/README.md) file was updated.

**Comment by mbardelmeijer** [comment]
@vmitchell85 perfect! Just installed the release candidate in our project and all seems to working nicely 👍

**Comment by vmitchell85** [comment]
@mbardelmeijer Done, sorry for the delay.

**Comment by mbardelmeijer** [comment]
@vmitchell85 no worries! I think the 2.0 tag now is based on `master`, where as the code is still on `develop`. Could you merge that into master and retag it? Thanks 🙏

**Comment by vmitchell85** [comment]
@mbardelmeijer that is what I get for moving too fast... LOL

**Pull request merged**
